### ISSUE TITLE
Documento de visão - Criar requisitos funcionais

### ISSUE THREAD

**Issue by JFmaia** [JFmaia/BsIn#1]
Nessa tarefa deve ser feito a criação dos requisitos funcionais, sempre prezando simplificar os requisitos ao máximo.

Obs: Essa tarefa é de suma importância e o analista deve estar em contato com o gerente e os outros membros para tirar qualquer duvida.

@FlaviodosSantos 

[Link para exemplo de Documento de Visão](https://github.com/tacianosilva/eng-software-2/blob/master/docs/doc-visao.md)

**Comment by FlaviodosSantos** [comment]
## Lista de Requisitos Funcionais

Requisito                                 | Descrição   | Ator |
---------                                 | ----------- | ---------- |
RF001 - Manter um cadastro de Autores | Cadastro de autores/administradores dos posts do blog | Autor |
RF002 - Manter um cadastro de Post | Cadastro dos post | Autor |
RF003 - Manter um cadastro para os Comentarios | Administrar os comentarios: autorizar ou apagar-los | Autor |
RF004 - Manter um cadastro para os Usuários | Usuários externos só podem comentar depois de logado | Autor |
